[package]
name = "termail"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
lettre = "0.10.0-rc.6"
imap = "3.0.0-alpha.7"
dotenv = "0.15.0"